name: Apply PR Template Based on Target Branch
on:
  pull_request:
    types: [opened, edited]

jobs:
  set-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Details (Number, Target Branch, Body)
        id: get_pr
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          TARGET_BRANCH=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
          PR_BODY=$(jq --raw-output .pull_request.body "$GITHUB_EVENT_PATH")

          # Convert "null" to an empty string
          if [[ "$PR_BODY" == "null" ]]; then
            PR_BODY=""
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

      - name: Debug PR Body
        run: echo "Processed PR_BODY='$PR_BODY'"

      - name: Set PR Template if Target Branch Matches & PR Body is Empty
        if: contains(env.TARGET_BRANCH, 'ui/web/release')
        run: |
          if [[ -z "$PR_BODY" ]]; then
            PR_TEMPLATE=$(cat .github/PULL_REQUEST_TEMPLATE/project-one-template.md)
            gh pr edit $PR_NUMBER --body "$PR_TEMPLATE"
          else
            echo "PR Body is not empty, skipping template update."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

